baseURL = "https://KatyaZubareva.github.io/web-portfolio/"
languageCode = "en-us"
title = "–ü–æ—Ä—Ç—Ñ–æ–ª–∏–æ"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "–û–±–æ –º–Ω–µ"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "–ú–æ–∏ –ø—Ä–æ–µ–∫—Ç—ã"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "HTTP"
    url = "/http/"
    weight = 3

[pagination]
  pagerSize = 10

[params]
  author = "–ö–∞—Ç—è –ó—É–±–∞—Ä–µ–≤–∞"
  defaultTheme = "auto"
  showPosts = false

  [params.homeInfoParams]
    Title = "üå∫ –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å!"
    Content = """
–ú–µ–Ω—è –∑–æ–≤—É—Ç **–ï–∫–∞—Ç–µ—Ä–∏–Ω–∞**.  
–Ø UI/UX –¥–∏–∑–∞–π–Ω–µ—Ä –∏ —Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫ —Ü–∏—Ñ—Ä–æ–≤—ã—Ö –ø—Ä–æ–¥—É–∫—Ç–æ–≤.

–°–æ–∑–¥–∞—é –ø–æ–Ω—è—Ç–Ω—ã–µ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å—ã, –ø—Ä–æ–¥—É–º–∞–Ω–Ω—ã–µ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å—Å–∫–∏–µ —Å—Ü–µ–Ω–∞—Ä–∏–∏  
–∏ –≤–∏–∑—É–∞–ª—å–Ω—ã–µ —Ä–µ—à–µ–Ω–∏—è, –∫–æ—Ç–æ—Ä—ã–µ —Ä–∞–±–æ—Ç–∞—é—Ç –Ω–∞ —Ä–µ–∑—É–ª—å—Ç–∞—Ç.
"""
